taxonomy: topic
_id: ai-in-security
name: AI in Security
shortname: Security
parent: AI
keywords:
  - security
hashtags:
  - "#security"
images:
  - https://smartableai.github.io/artificial-intelligence/assets/images/topics/ai-in-security.jpg
services:
  companies: https://smartableai.github.io/artificial-intelligence/api/companies/ai-in-security/
---